name: Update CKEditor 4 submodule

on:
  schedule:
  - cron: "0 0,10,16 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master, major]

    steps:
      - name: Fetch changes
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Prepare update
        run: |
          branch=$(git rev-parse --abbrev-ref HEAD)
          echo "Updating ckeditor4 submodule on ckeditor4-presets $branch branch..."

          git submodule update --init --recursive

          # Updates ckeditor submodule branch.
          echo "Fetching latest ckeditor4 changes from $branch branch..."

          cd "ckeditor"
          oldHash=$(git log -1 --format="%h")
          git fetch --all -p
          git reset --hard "origin/$branch"
          newHash=$(git log -1 --format="%h")

          # Checks if anything changed and prepares commit.
          if [ "$oldHash" = "$newHash" ]; then
            echo "Nothing changed (still on the latest $oldHash commit), aboritng..."
          else
            echo "Preparing update for $branch branch from $oldHash to $newHash..."

            cd ".."
            git config --local user.email "ckeditor-bot@cksource.com"
            git config --local user.name "CKEditor Bot"
            git add ckeditor
            git commit -m "Update CKEditor 4 submodule HEAD."
          fi

      - name: Push changes
        # https://github.com/marketplace/actions/github-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.branch }}
