name: Update CKEditor 4 submodule

on:
  schedule:
  - cron: "0 0,10,16 * * *"

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [master, major]

    steps:
      - name: Fetch changes
        # https://github.com/marketplace/actions/checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Prepare update
        run: |
          ./dev/workflows/ckeditorupdate.sh

      - name: Push changes
        # https://github.com/marketplace/actions/github-push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ matrix.branch }}
